# Generated by Django 4.0.1 on 2022-01-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EOIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eoic_id', models.IntegerField()),
                ('vl_result', models.CharField(max_length=50)),
                ('investigation_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('staff_initials', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('enrollment_date', models.DateField()),
                ('staff_initials', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rerand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rerand_id', models.IntegerField()),
                ('rerand_date', models.DateField()),
                ('vl_results', models.CharField(max_length=50)),
                ('rerand_arm', models.CharField(max_length=50)),
                ('staff_initials', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viralload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viral_id', models.IntegerField()),
                ('date_collection', models.DateField()),
                ('vl_results', models.CharField(max_length=50)),
                ('date_received', models.DateField()),
                ('date_entered', models.DateField()),
                ('staff_initials', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VLMONTH6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month6_id', models.IntegerField()),
                ('collection_date', models.DateField()),
                ('vl_result', models.CharField(max_length=50)),
                ('vl_suppressed', models.CharField(max_length=50)),
                ('date_received', models.DateField()),
                ('staff_initials', models.CharField(max_length=50)),
            ],
        ),
    ]
