# Generated by Django 4.0.1 on 2022-02-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_viralload_viral_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viralload',
            old_name='viral_id',
            new_name='participants',
        ),
    ]
