# Generated by Django 4.0.1 on 2022-02-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_rerand_rerand_id_rerand_participants_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rerand',
            old_name='participants_id',
            new_name='participants',
        ),
    ]
