# Generated by Django 4.0.1 on 2022-02-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_participants_id_rerand_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rerand',
            old_name='viralload_id',
            new_name='viralload',
        ),
    ]
