# Generated by Django 4.0.1 on 2022-02-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_rename_viralload_id_rerand_viralload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlmonth6',
            name='month6_id',
        ),
        migrations.AddField(
            model_name='vlmonth6',
            name='participants',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.participants'),
        ),
        migrations.AddField(
            model_name='vlmonth6',
            name='rerand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.rerand'),
        ),
    ]
