# Generated by Django 4.0.1 on 2022-02-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_vlmonth6_month6_id_vlmonth6_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlmonth6',
            name='vl_suppressed',
            field=models.IntegerField(),
        ),
    ]
